## Avance 2: Proceso de Extracción y Transformación (Yelp API)

##### 2.1 Configuración del Entorno e Importación

In [1]:
import pandas as pd
import requests
import numpy as np
import openpyxl
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:

#url de la API
api_url='https://api.yelp.com/v3/businesses/search'

#estos datos corresponden a una cuenta de usuario creada previamente
clientid='GWOCZh9-BmZxtdsAjr7Gug'
apikey='FHVvXoNmTXIl9DuxYis7AV5uLPujm9MLwrhgs5NgvCfaOxd3V6mxt6dQU8eEqYJiGxe816XATx7ufWjbMWqbV-2Uku1jxBJv8BGRC74NroLPl27PDQqs0tDixit-YHYx'
headers={'Authorization':'Bearer %s'%apikey}

In [4]:
ciudad = "Miami" # Se puede elegir cualquier ciudad del dataset entregado

#### 2.2 Extracción de Datos vía API (Request)

In [5]:
# De esta manera se consulta el API de Yelp para obtener información sobre restaurantes en la ciudad especificada
params={'term':'restaurants','location': ciudad,'limit':50}
response=requests.get(api_url,params=params,headers=headers)
data=response.json()
data

{'businesses': [{'id': 'K3ukx2e11xTRtYBU01dmrA',
   'alias': 'salty-flame-miami',
   'name': 'Salty Flame',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/_6wShTvzfucB5dxFZv4Mpg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/salty-flame-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 258,
   'categories': [{'alias': 'asianfusion', 'title': 'Asian Fusion'},
    {'alias': 'steak', 'title': 'Steakhouses'},
    {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}],
   'rating': 4.3,
   'coordinates': {'latitude': 25.76022, 'longitude': -80.19267},
   'transactions': ['delivery', 'pickup'],
   'location': {'address1': '1414 Brickell Ave',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33131',
    'country': 'US',
    'state': 'FL',
    'display_address': ['1414 Brickell Ave', 'Miami, FL 33131']},
   'phone': '+13055638972',
   'display_phone': '(305) 563-8972',
   'distance': 9568.050891007853},
  {'id': 'UXHxLN3DcDGI57uDIfCuJA',
   'alias': 'olds-havana-cuban-bar-and-cocina-miami',
   'name': "Old's Havana Cuban Bar & Cocina",
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/OyMD-xvBjobfDmDdBs2Jfw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/olds-havana-cuban-bar-and-cocina-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 3192,
   'categories': [{'alias': 'cuban', 'title': 'Cuban'},
    {'alias': 'bars', 'title': 'Bars'},
    {'alias': 'venues', 'title': 'Venues & Event Spaces'}],
   'rating': 4.4,
   'coordinates': {'latitude': 25.765607074496565,
    'longitude': -80.21921771559332},
   'transactions': ['pickup', 'restaurant_reservation'],
   'price': '$$',
   'location': {'address1': '1442 SW 8th St',
    'address2': '',
    'address3': None,
    'city': 'Miami',
    'zip_code': '33135',
    'country': 'US',
    'state': 'FL',
    'display_address': ['1442 SW 8th St', 'Miami, FL 33135']},
   'phone': '+17865182196',
   'display_phone': '(786) 518-2196',
   'distance': 7038.216305367002},
  {'id': 'oxtMfBGmVNE18pFVuw7lFg',
   'alias': 'fratellino-coral-gables-2',
   'name': 'Fratellino',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/OPS9ibIzgVyzcJ3ZyNf9IQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/fratellino-coral-gables-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1901,
   'categories': [{'alias': 'italian', 'title': 'Italian'}],
   'rating': 4.8,
   'coordinates': {'latitude': 25.74917, 'longitude': -80.26011},
   'transactions': ['delivery', 'pickup', 'restaurant_reservation'],
   'price': '$$$',
   'location': {'address1': '264 Miracle Mile',
    'address2': '',
    'address3': '',
    'city': 'Coral Gables',
    'zip_code': '33134',
    'country': 'US',
    'state': 'FL',
    'display_address': ['264 Miracle Mile', 'Coral Gables, FL 33134']},
   'phone': '+17864520068',
   'display_phone': '(786) 452-0068',
   'distance': 2834.064936518243},
  {'id': 'O4gh_gZPp1zW9QtC1aMHWw',
   'alias': 'house-of-food-porn-miami-3',
   'name': 'House of Food Porn',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/YZJP20cFtRP73YEsp69aDA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/house-of-food-porn-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 178,
   'categories': [{'alias': 'sushi', 'title': 'Sushi Bars'},
    {'alias': 'asianfusion', 'title': 'Asian Fusion'},
    {'alias': 'wine_bars', 'title': 'Wine Bars'}],
   'rating': 4.8,
   'coordinates': {'latitude': 25.8326319884545,
    'longitude': -80.200107379434},
   'transactions': [],
   'location': {'address1': '197 NW 62nd St',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33150',
    'country': 'US',
    'state': 'FL',
    'display_address': ['197 NW 62nd St', 'Miami, FL 33150']},
   'phone': '+13057880137',
   'display_phone': '(305) 788-0137',
   'distance': 12507.730930037038},
  {'id': 'ix8ifP1jQM9ektdVAs19sQ',
   'alias': 'crazy-about-you-miami-3',
   'name': 'Crazy About You',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/C8cICmnvi0GRzr4OIwg6vQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/crazy-about-you-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 2882,
   'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
    {'alias': 'italian', 'title': 'Italian'},
    {'alias': 'spanish', 'title': 'Spanish'}],
   'rating': 4.2,
   'coordinates': {'latitude': 25.762015277335745,
    'longitude': -80.1889859201474},
   'transactions': ['delivery'],
   'price': '$$$',
   'location': {'address1': '1155 Brickell Bay Dr',
    'address2': 'Ste 101',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33131',
    'country': 'US',
    'state': 'FL',
    'display_address': ['1155 Brickell Bay Dr', 'Ste 101', 'Miami, FL 33131']},
   'phone': '+13053774442',
   'display_phone': '(305) 377-4442',
   'distance': 9973.468955482575},
  {'id': '_tiVacKyfWZjOljFenLwVQ',
   'alias': 'giselle-miami-miami',
   'name': 'Giselle Miami',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/tMrFekA5lavl0IHHuyVwHg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/giselle-miami-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 497,
   'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
    {'alias': 'lounges', 'title': 'Lounges'},
    {'alias': 'asianfusion', 'title': 'Asian Fusion'}],
   'rating': 4.6,
   'coordinates': {'latitude': 25.78496366, 'longitude': -80.19341399},
   'transactions': [],
   'location': {'address1': '15 NE 11th St',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33132',
    'country': 'US',
    'state': 'FL',
    'display_address': ['15 NE 11th St', 'Miami, FL 33132']},
   'phone': '+13053589848',
   'display_phone': '(305) 358-9848',
   'distance': 10127.920790439312},
  {'id': 'WqIBKxRUPXH3NqTViAHLxQ',
   'alias': 'bayshore-club-bar-and-grill-miami',
   'name': 'Bayshore Club Bar & Grill',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/B7tTbJMlp7Dk6rpE4P3j5Q/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/bayshore-club-bar-and-grill-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1039,
   'categories': [{'alias': 'seafood', 'title': 'Seafood'},
    {'alias': 'tradamerican', 'title': 'American'},
    {'alias': 'wine_bars', 'title': 'Wine Bars'}],
   'rating': 4.3,
   'coordinates': {'latitude': 25.72877375829567, 'longitude': -80.2341624},
   'transactions': [],
   'price': '$$$',
   'location': {'address1': '3391 Pan American Dr',
    'address2': None,
    'address3': None,
    'city': 'Miami',
    'zip_code': '33133',
    'country': 'US',
    'state': 'FL',
    'display_address': ['3391 Pan American Dr', 'Miami, FL 33133']},
   'phone': '+13052091200',
   'display_phone': '(305) 209-1200',
   'distance': 6023.917796785677},
  {'id': 'rf9zxndiD2k4hXwBAtQMrQ',
   'alias': 'kpot-korean-bbq-and-hot-pot-miami-2',
   'name': 'KPOT Korean BBQ & Hot Pot',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/UQ65jDW_LSIGuMLEdEACYg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/kpot-korean-bbq-and-hot-pot-miami-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 15,
   'categories': [{'alias': 'korean', 'title': 'Korean'},
    {'alias': 'bbq', 'title': 'Barbeque'},
    {'alias': 'hotpot', 'title': 'Hot Pot'}],
   'rating': 4.6,
   'coordinates': {'latitude': 25.77196, 'longitude': -80.32905},
   'transactions': [],
   'location': {'address1': '8255 W Flagler St',
    'address2': '',
    'address3': None,
    'city': 'Miami',
    'zip_code': '33144',
    'country': 'US',
    'state': 'FL',
    'display_address': ['8255 W Flagler St', 'Miami, FL 33144']},
   'phone': '+17866368137',
   'display_phone': '(786) 636-8137',
   'distance': 4624.134435770181},
  {'id': 'eVhl0Yu1ZRWRD2D1OQGsYg',
   'alias': 'capriccio-miami-13',
   'name': 'Capriccio',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XvLWJxAVk_KVc2Ucr5Lh9A/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/capriccio-miami-13?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 170,
   'categories': [{'alias': 'italian', 'title': 'Italian'},
    {'alias': 'pizza', 'title': 'Pizza'},
    {'alias': 'steak', 'title': 'Steakhouses'}],
   'rating': 4.5,
   'coordinates': {'latitude': 25.781633128697905,
    'longitude': -80.28766177465242},
   'transactions': ['restaurant_reservation'],
   'location': {'address1': '5600 Blue Lagoon Dr',
    'address2': 'Ste 9',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33126',
    'country': 'US',
    'state': 'FL',
    'display_address': ['5600 Blue Lagoon Dr', 'Ste 9', 'Miami, FL 33126']},
   'phone': '+17869365470',
   'display_phone': '(786) 936-5470',
   'distance': 3203.121202511091},
  {'id': 'nwY3CmIH75cN85cWBSaOAw',
   'alias': 'apocalypse-bbq-miami',
   'name': 'Apocalypse BBQ',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/dnWRHDwSOApEyxPoZZRFLA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/apocalypse-bbq-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1154,
   'categories': [{'alias': 'foodtrucks', 'title': 'Food Trucks'},
    {'alias': 'bbq', 'title': 'Barbeque'},
    {'alias': 'empanadas', 'title': 'Empanadas'}],
   'rating': 4.4,
   'coordinates': {'latitude': 25.68797, 'longitude': -80.3936},
   'transactions': [],
   'price': '$$',
   'location': {'address1': '8695 SW 124th Ave',
    'address2': '',
    'address3': None,
    'city': 'Miami',
    'zip_code': '33183',
    'country': 'US',
    'state': 'FL',
    'display_address': ['8695 SW 124th Ave', 'Miami, FL 33183']},
   'phone': '',
   'display_phone': '',
   'distance': 12797.71127183584},
  {'id': 'hZm7TunlrksQbgS0ssXbUg',
   'alias': 'versailles-miami-4',
   'name': 'Versailles',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/q_T1_ShhFe0CuPaNtvzLXQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/versailles-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 7019,
   'categories': [{'alias': 'cuban', 'title': 'Cuban'},
    {'alias': 'coffee', 'title': 'Coffee & Tea'},
    {'alias': 'sandwiches', 'title': 'Sandwiches'}],
   'rating': 4.0,
   'coordinates': {'latitude': 25.765389817507295,
    'longitude': -80.25287416592283},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '3555 SW 8th St',
    'address2': '',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33135',
    'country': 'US',
    'state': 'FL',
    'display_address': ['3555 SW 8th St', 'Miami, FL 33135']},
   'phone': '+13054440240',
   'display_phone': '(305) 444-0240',
   'distance': 3789.5569842271616},
  {'id': 'scZfLg-ujWMEOUmFM_Qalg',
   'alias': 'don-maguey-mexican-restaurant-miami',
   'name': 'Don Maguey Mexican Restaurant',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/emYsWIbH0iMFabrWd3lClQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/don-maguey-mexican-restaurant-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 305,
   'categories': [{'alias': 'mexican', 'title': 'Mexican'}],
   'rating': 4.7,
   'coordinates': {'latitude': 25.7717682877048,
    'longitude': -80.27253760250089},
   'transactions': ['pickup'],
   'price': '$$',
   'location': {'address1': '4747 W Flagler St',
    'address2': '',
    'address3': None,
    'city': 'Miami',
    'zip_code': '33134',
    'country': 'US',
    'state': 'FL',
    'display_address': ['4747 W Flagler St', 'Miami, FL 33134']},
   'phone': '+17865585650',
   'display_phone': '(786) 558-5650',
   'distance': 2616.9735888249156},
  {'id': 'QQnw1bFxLyamuxn4giIy9g',
   'alias': 'sufrat-mediterranean-grill-miami-4',
   'name': 'Sufrat Mediterranean Grill',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Z5Q7D855uiOO8WKuDn-eGQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/sufrat-mediterranean-grill-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 150,
   'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
    {'alias': 'greek', 'title': 'Greek'},
    {'alias': 'lebanese', 'title': 'Lebanese'}],
   'rating': 4.5,
   'coordinates': {'latitude': 25.82001, 'longitude': -80.335628},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '8455 NW 53rd St',
    'address2': 'Suite 106',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33166',
    'country': 'US',
    'state': 'FL',
    'display_address': ['8455 NW 53rd St', 'Suite 106', 'Miami, FL 33166']},
   'phone': '+13057987278',
   'display_phone': '(305) 798-7278',
   'distance': 8884.862194544405},
  {'id': 'LPVv4wk9gwGlIEdfZJRaHQ',
   'alias': 'jrk-miami-miami',
   'name': 'Jrk!',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/nB_I7hx4NhhBv5oYF1tDdA/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/jrk-miami-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 130,
   'categories': [{'alias': 'caribbean', 'title': 'Caribbean'}],
   'rating': 4.5,
   'coordinates': {'latitude': 25.775205782261285,
    'longitude': -80.19496699999999},
   'transactions': [],
   'price': '$$',
   'location': {'address1': '95 NW 1st St',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33128',
    'country': 'US',
    'state': 'FL',
    'display_address': ['95 NW 1st St', 'Miami, FL 33128']},
   'phone': '+13052904684',
   'display_phone': '(305) 290-4684',
   'distance': 9647.891842653617},
  {'id': 'V3btCvWa1flTBYt2YKea_g',
   'alias': 'bombay-darbar-miami-3',
   'name': 'Bombay Darbar',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ZYRyJ1_iTHzLBr37P78vow/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/bombay-darbar-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 1714,
   'categories': [{'alias': 'indpak', 'title': 'Indian'}],
   'rating': 4.5,
   'coordinates': {'latitude': 25.72935, 'longitude': -80.240789},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '2901 Florida Ave',
    'address2': '',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33133',
    'country': 'US',
    'state': 'FL',
    'display_address': ['2901 Florida Ave', 'Miami, FL 33133']},
   'phone': '+13054447272',
   'display_phone': '(305) 444-7272',
   'distance': 5405.961958481842},
  {'id': 'Jjifi324EdbrMWSW2-ZcKQ',
   'alias': 'homa-persian-cuisine-miami',
   'name': 'Homa Persian Cuisine',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Tf9Lr5KdZavRWCH7qJNFZg/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/homa-persian-cuisine-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 40,
   'categories': [{'alias': 'persian', 'title': 'Persian/Iranian'}],
   'rating': 4.8,
   'coordinates': {'latitude': 25.746275, 'longitude': -80.221992},
   'transactions': ['delivery', 'pickup'],
   'location': {'address1': '2490 SW 17th Ave',
    'address2': None,
    'address3': None,
    'city': 'Miami',
    'zip_code': '33145',
    'country': 'US',
    'state': 'FL',
    'display_address': ['2490 SW 17th Ave', 'Miami, FL 33145']},
   'phone': '+13052522222',
   'display_phone': '(305) 252-2222',
   'distance': 6654.565051559707},
  {'id': 'zUgXGynAq6_VptoNO50IhA',
   'alias': 'sparrow-italia-miami-4',
   'name': 'Sparrow Italia',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ARvaw7p77Cs8PTjFw3J3Yw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/sparrow-italia-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 194,
   'categories': [{'alias': 'italian', 'title': 'Italian'}],
   'rating': 4.4,
   'coordinates': {'latitude': 25.80089918437128,
    'longitude': -80.20045189999999},
   'transactions': [],
   'price': '$$$',
   'location': {'address1': '255 NW 25th St',
    'address2': 'Fl 1',
    'address3': '',
    'city': 'Miami',
    'zip_code': '33127',
    'country': 'US',
    'state': 'FL',
    'display_address': ['255 NW 25th St', 'Fl 1', 'Miami, FL 33127']},
   'phone': '+17863225998',
   'display_phone': '(786) 322-5998',
   'distance': 10271.640964643853},
  {'id': 'bcjpKKj5cnfg8fvmMeVyfw',
   'alias': 'fooqs-miami-5',
   'name': "Fooq's",
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/lfIDUgz4naQ6f0XyHtjEPw/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/fooqs-miami-5?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 16,
   'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'}],
   'rating': 4.4,
   'coordinates': {'latitude': 25.8419927, 'longitude': -80.1991753},
   'transactions': [],
   'location': {'address1': '150 NW 73rd St',
    'address2': None,
    'address3': None,
    'city': 'Miami',
    'zip_code': '33150',
    'country': 'US',
    'state': 'FL',
    'display_address': ['150 NW 73rd St', 'Miami, FL 33150']},
   'phone': '+17862149076',
   'display_phone': '(786) 214-9076',
   'distance': 13321.616279262873},
  {'id': 'z1UW-zeI50bMEtGKFtrjmA',
   'alias': 'grails-miami-restaurant-and-sports-bar-miami',
   'name': 'Grails Miami - Restaurant & Sports Bar',
   'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XU08RveGxutYa-B_2qcClQ/o.jpg',
   'is_closed': False,
   'url': 'https://www.yelp.com/biz/grails-miami-restaurant-and-sports-bar-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
   'review_count': 776,
   'categories': [{'alias': 'sportsbars', 'title': 'Sports Bars'},
    {'alias': 'newamerican', 'title': 'New American'},
    {'alias': 'lounges', 'title': 'Lounges'}],
   'rating': 4.4,
   'coordinates': {'latitude': 25.803184, 'longitude': -80.195219},
   'transactions': ['delivery', 'pickup'],
   'price': '$$',
   'location': {'address1': '2800 N Miami Ave',
    'address2': None,
    'address3': '',
    'city': 'Miami',
    'zip_code': '33127',
    'country': 'US',
    'state': 'FL',
    'display_address': ['2800 N Miami Ave', 'Miami, FL 33127']},
   'phone': '+17868704313',
   'display_phone': '(786) 870-4313',

In [6]:
#Veamos los keys del diccionario recibido
data.keys()

dict_keys(['businesses', 'total', 'region'])

In [7]:
#El primer elemento del diccionario indica el total de restaurants existentes en la API
print('En total la base de datos registra %d restaurants'%data['total'])

En total la base de datos registra 5800 restaurants

In [8]:
data['businesses'] # Hasta acá se le entregaría a los estudiantes

[{'id': 'K3ukx2e11xTRtYBU01dmrA',
  'alias': 'salty-flame-miami',
  'name': 'Salty Flame',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/_6wShTvzfucB5dxFZv4Mpg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/salty-flame-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 258,
  'categories': [{'alias': 'asianfusion', 'title': 'Asian Fusion'},
   {'alias': 'steak', 'title': 'Steakhouses'},
   {'alias': 'cocktailbars', 'title': 'Cocktail Bars'}],
  'rating': 4.3,
  'coordinates': {'latitude': 25.76022, 'longitude': -80.19267},
  'transactions': ['delivery', 'pickup'],
  'location': {'address1': '1414 Brickell Ave',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33131',
   'country': 'US',
   'state': 'FL',
   'display_address': ['1414 Brickell Ave', 'Miami, FL 33131']},
  'phone': '+13055638972',
  'display_phone': '(305) 563-8972',
  'distance': 9568.050891007853},
 {'id': 'UXHxLN3DcDGI57uDIfCuJA',
  'alias': 'olds-havana-cuban-bar-and-cocina-miami',
  'name': "Old's Havana Cuban Bar & Cocina",
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/OyMD-xvBjobfDmDdBs2Jfw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/olds-havana-cuban-bar-and-cocina-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 3192,
  'categories': [{'alias': 'cuban', 'title': 'Cuban'},
   {'alias': 'bars', 'title': 'Bars'},
   {'alias': 'venues', 'title': 'Venues & Event Spaces'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.765607074496565,
   'longitude': -80.21921771559332},
  'transactions': ['pickup', 'restaurant_reservation'],
  'price': '$$',
  'location': {'address1': '1442 SW 8th St',
   'address2': '',
   'address3': None,
   'city': 'Miami',
   'zip_code': '33135',
   'country': 'US',
   'state': 'FL',
   'display_address': ['1442 SW 8th St', 'Miami, FL 33135']},
  'phone': '+17865182196',
  'display_phone': '(786) 518-2196',
  'distance': 7038.216305367002},
 {'id': 'oxtMfBGmVNE18pFVuw7lFg',
  'alias': 'fratellino-coral-gables-2',
  'name': 'Fratellino',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/OPS9ibIzgVyzcJ3ZyNf9IQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/fratellino-coral-gables-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1901,
  'categories': [{'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.8,
  'coordinates': {'latitude': 25.74917, 'longitude': -80.26011},
  'transactions': ['delivery', 'pickup', 'restaurant_reservation'],
  'price': '$$$',
  'location': {'address1': '264 Miracle Mile',
   'address2': '',
   'address3': '',
   'city': 'Coral Gables',
   'zip_code': '33134',
   'country': 'US',
   'state': 'FL',
   'display_address': ['264 Miracle Mile', 'Coral Gables, FL 33134']},
  'phone': '+17864520068',
  'display_phone': '(786) 452-0068',
  'distance': 2834.064936518243},
 {'id': 'O4gh_gZPp1zW9QtC1aMHWw',
  'alias': 'house-of-food-porn-miami-3',
  'name': 'House of Food Porn',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/YZJP20cFtRP73YEsp69aDA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/house-of-food-porn-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 178,
  'categories': [{'alias': 'sushi', 'title': 'Sushi Bars'},
   {'alias': 'asianfusion', 'title': 'Asian Fusion'},
   {'alias': 'wine_bars', 'title': 'Wine Bars'}],
  'rating': 4.8,
  'coordinates': {'latitude': 25.8326319884545, 'longitude': -80.200107379434},
  'transactions': [],
  'location': {'address1': '197 NW 62nd St',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33150',
   'country': 'US',
   'state': 'FL',
   'display_address': ['197 NW 62nd St', 'Miami, FL 33150']},
  'phone': '+13057880137',
  'display_phone': '(305) 788-0137',
  'distance': 12507.730930037038},
 {'id': 'ix8ifP1jQM9ektdVAs19sQ',
  'alias': 'crazy-about-you-miami-3',
  'name': 'Crazy About You',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/C8cICmnvi0GRzr4OIwg6vQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/crazy-about-you-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 2882,
  'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'italian', 'title': 'Italian'},
   {'alias': 'spanish', 'title': 'Spanish'}],
  'rating': 4.2,
  'coordinates': {'latitude': 25.762015277335745,
   'longitude': -80.1889859201474},
  'transactions': ['delivery'],
  'price': '$$$',
  'location': {'address1': '1155 Brickell Bay Dr',
   'address2': 'Ste 101',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33131',
   'country': 'US',
   'state': 'FL',
   'display_address': ['1155 Brickell Bay Dr', 'Ste 101', 'Miami, FL 33131']},
  'phone': '+13053774442',
  'display_phone': '(305) 377-4442',
  'distance': 9973.468955482575},
 {'id': '_tiVacKyfWZjOljFenLwVQ',
  'alias': 'giselle-miami-miami',
  'name': 'Giselle Miami',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/tMrFekA5lavl0IHHuyVwHg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/giselle-miami-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 497,
  'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'lounges', 'title': 'Lounges'},
   {'alias': 'asianfusion', 'title': 'Asian Fusion'}],
  'rating': 4.6,
  'coordinates': {'latitude': 25.78496366, 'longitude': -80.19341399},
  'transactions': [],
  'location': {'address1': '15 NE 11th St',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33132',
   'country': 'US',
   'state': 'FL',
   'display_address': ['15 NE 11th St', 'Miami, FL 33132']},
  'phone': '+13053589848',
  'display_phone': '(305) 358-9848',
  'distance': 10127.920790439312},
 {'id': 'WqIBKxRUPXH3NqTViAHLxQ',
  'alias': 'bayshore-club-bar-and-grill-miami',
  'name': 'Bayshore Club Bar & Grill',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/B7tTbJMlp7Dk6rpE4P3j5Q/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/bayshore-club-bar-and-grill-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1039,
  'categories': [{'alias': 'seafood', 'title': 'Seafood'},
   {'alias': 'tradamerican', 'title': 'American'},
   {'alias': 'wine_bars', 'title': 'Wine Bars'}],
  'rating': 4.3,
  'coordinates': {'latitude': 25.72877375829567, 'longitude': -80.2341624},
  'transactions': [],
  'price': '$$$',
  'location': {'address1': '3391 Pan American Dr',
   'address2': None,
   'address3': None,
   'city': 'Miami',
   'zip_code': '33133',
   'country': 'US',
   'state': 'FL',
   'display_address': ['3391 Pan American Dr', 'Miami, FL 33133']},
  'phone': '+13052091200',
  'display_phone': '(305) 209-1200',
  'distance': 6023.917796785677},
 {'id': 'rf9zxndiD2k4hXwBAtQMrQ',
  'alias': 'kpot-korean-bbq-and-hot-pot-miami-2',
  'name': 'KPOT Korean BBQ & Hot Pot',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/UQ65jDW_LSIGuMLEdEACYg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/kpot-korean-bbq-and-hot-pot-miami-2?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 15,
  'categories': [{'alias': 'korean', 'title': 'Korean'},
   {'alias': 'bbq', 'title': 'Barbeque'},
   {'alias': 'hotpot', 'title': 'Hot Pot'}],
  'rating': 4.6,
  'coordinates': {'latitude': 25.77196, 'longitude': -80.32905},
  'transactions': [],
  'location': {'address1': '8255 W Flagler St',
   'address2': '',
   'address3': None,
   'city': 'Miami',
   'zip_code': '33144',
   'country': 'US',
   'state': 'FL',
   'display_address': ['8255 W Flagler St', 'Miami, FL 33144']},
  'phone': '+17866368137',
  'display_phone': '(786) 636-8137',
  'distance': 4624.134435770181},
 {'id': 'eVhl0Yu1ZRWRD2D1OQGsYg',
  'alias': 'capriccio-miami-13',
  'name': 'Capriccio',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XvLWJxAVk_KVc2Ucr5Lh9A/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/capriccio-miami-13?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 170,
  'categories': [{'alias': 'italian', 'title': 'Italian'},
   {'alias': 'pizza', 'title': 'Pizza'},
   {'alias': 'steak', 'title': 'Steakhouses'}],
  'rating': 4.5,
  'coordinates': {'latitude': 25.781633128697905,
   'longitude': -80.28766177465242},
  'transactions': ['restaurant_reservation'],
  'location': {'address1': '5600 Blue Lagoon Dr',
   'address2': 'Ste 9',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33126',
   'country': 'US',
   'state': 'FL',
   'display_address': ['5600 Blue Lagoon Dr', 'Ste 9', 'Miami, FL 33126']},
  'phone': '+17869365470',
  'display_phone': '(786) 936-5470',
  'distance': 3203.121202511091},
 {'id': 'nwY3CmIH75cN85cWBSaOAw',
  'alias': 'apocalypse-bbq-miami',
  'name': 'Apocalypse BBQ',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/dnWRHDwSOApEyxPoZZRFLA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/apocalypse-bbq-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1154,
  'categories': [{'alias': 'foodtrucks', 'title': 'Food Trucks'},
   {'alias': 'bbq', 'title': 'Barbeque'},
   {'alias': 'empanadas', 'title': 'Empanadas'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.68797, 'longitude': -80.3936},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '8695 SW 124th Ave',
   'address2': '',
   'address3': None,
   'city': 'Miami',
   'zip_code': '33183',
   'country': 'US',
   'state': 'FL',
   'display_address': ['8695 SW 124th Ave', 'Miami, FL 33183']},
  'phone': '',
  'display_phone': '',
  'distance': 12797.71127183584},
 {'id': 'hZm7TunlrksQbgS0ssXbUg',
  'alias': 'versailles-miami-4',
  'name': 'Versailles',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/q_T1_ShhFe0CuPaNtvzLXQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/versailles-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 7019,
  'categories': [{'alias': 'cuban', 'title': 'Cuban'},
   {'alias': 'coffee', 'title': 'Coffee & Tea'},
   {'alias': 'sandwiches', 'title': 'Sandwiches'}],
  'rating': 4.0,
  'coordinates': {'latitude': 25.765389817507295,
   'longitude': -80.25287416592283},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '3555 SW 8th St',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33135',
   'country': 'US',
   'state': 'FL',
   'display_address': ['3555 SW 8th St', 'Miami, FL 33135']},
  'phone': '+13054440240',
  'display_phone': '(305) 444-0240',
  'distance': 3789.5569842271616},
 {'id': 'scZfLg-ujWMEOUmFM_Qalg',
  'alias': 'don-maguey-mexican-restaurant-miami',
  'name': 'Don Maguey Mexican Restaurant',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/emYsWIbH0iMFabrWd3lClQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/don-maguey-mexican-restaurant-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 305,
  'categories': [{'alias': 'mexican', 'title': 'Mexican'}],
  'rating': 4.7,
  'coordinates': {'latitude': 25.7717682877048,
   'longitude': -80.27253760250089},
  'transactions': ['pickup'],
  'price': '$$',
  'location': {'address1': '4747 W Flagler St',
   'address2': '',
   'address3': None,
   'city': 'Miami',
   'zip_code': '33134',
   'country': 'US',
   'state': 'FL',
   'display_address': ['4747 W Flagler St', 'Miami, FL 33134']},
  'phone': '+17865585650',
  'display_phone': '(786) 558-5650',
  'distance': 2616.9735888249156},
 {'id': 'QQnw1bFxLyamuxn4giIy9g',
  'alias': 'sufrat-mediterranean-grill-miami-4',
  'name': 'Sufrat Mediterranean Grill',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Z5Q7D855uiOO8WKuDn-eGQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/sufrat-mediterranean-grill-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 150,
  'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'},
   {'alias': 'greek', 'title': 'Greek'},
   {'alias': 'lebanese', 'title': 'Lebanese'}],
  'rating': 4.5,
  'coordinates': {'latitude': 25.82001, 'longitude': -80.335628},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '8455 NW 53rd St',
   'address2': 'Suite 106',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33166',
   'country': 'US',
   'state': 'FL',
   'display_address': ['8455 NW 53rd St', 'Suite 106', 'Miami, FL 33166']},
  'phone': '+13057987278',
  'display_phone': '(305) 798-7278',
  'distance': 8884.862194544405},
 {'id': 'LPVv4wk9gwGlIEdfZJRaHQ',
  'alias': 'jrk-miami-miami',
  'name': 'Jrk!',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/nB_I7hx4NhhBv5oYF1tDdA/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/jrk-miami-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 130,
  'categories': [{'alias': 'caribbean', 'title': 'Caribbean'}],
  'rating': 4.5,
  'coordinates': {'latitude': 25.775205782261285,
   'longitude': -80.19496699999999},
  'transactions': [],
  'price': '$$',
  'location': {'address1': '95 NW 1st St',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33128',
   'country': 'US',
   'state': 'FL',
   'display_address': ['95 NW 1st St', 'Miami, FL 33128']},
  'phone': '+13052904684',
  'display_phone': '(305) 290-4684',
  'distance': 9647.891842653617},
 {'id': 'V3btCvWa1flTBYt2YKea_g',
  'alias': 'bombay-darbar-miami-3',
  'name': 'Bombay Darbar',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ZYRyJ1_iTHzLBr37P78vow/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/bombay-darbar-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 1714,
  'categories': [{'alias': 'indpak', 'title': 'Indian'}],
  'rating': 4.5,
  'coordinates': {'latitude': 25.72935, 'longitude': -80.240789},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '2901 Florida Ave',
   'address2': '',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33133',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2901 Florida Ave', 'Miami, FL 33133']},
  'phone': '+13054447272',
  'display_phone': '(305) 444-7272',
  'distance': 5405.961958481842},
 {'id': 'Jjifi324EdbrMWSW2-ZcKQ',
  'alias': 'homa-persian-cuisine-miami',
  'name': 'Homa Persian Cuisine',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/Tf9Lr5KdZavRWCH7qJNFZg/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/homa-persian-cuisine-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 40,
  'categories': [{'alias': 'persian', 'title': 'Persian/Iranian'}],
  'rating': 4.8,
  'coordinates': {'latitude': 25.746275, 'longitude': -80.221992},
  'transactions': ['delivery', 'pickup'],
  'location': {'address1': '2490 SW 17th Ave',
   'address2': None,
   'address3': None,
   'city': 'Miami',
   'zip_code': '33145',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2490 SW 17th Ave', 'Miami, FL 33145']},
  'phone': '+13052522222',
  'display_phone': '(305) 252-2222',
  'distance': 6654.565051559707},
 {'id': 'zUgXGynAq6_VptoNO50IhA',
  'alias': 'sparrow-italia-miami-4',
  'name': 'Sparrow Italia',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/ARvaw7p77Cs8PTjFw3J3Yw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/sparrow-italia-miami-4?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 194,
  'categories': [{'alias': 'italian', 'title': 'Italian'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.80089918437128,
   'longitude': -80.20045189999999},
  'transactions': [],
  'price': '$$$',
  'location': {'address1': '255 NW 25th St',
   'address2': 'Fl 1',
   'address3': '',
   'city': 'Miami',
   'zip_code': '33127',
   'country': 'US',
   'state': 'FL',
   'display_address': ['255 NW 25th St', 'Fl 1', 'Miami, FL 33127']},
  'phone': '+17863225998',
  'display_phone': '(786) 322-5998',
  'distance': 10271.640964643853},
 {'id': 'bcjpKKj5cnfg8fvmMeVyfw',
  'alias': 'fooqs-miami-5',
  'name': "Fooq's",
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/lfIDUgz4naQ6f0XyHtjEPw/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/fooqs-miami-5?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 16,
  'categories': [{'alias': 'mediterranean', 'title': 'Mediterranean'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.8419927, 'longitude': -80.1991753},
  'transactions': [],
  'location': {'address1': '150 NW 73rd St',
   'address2': None,
   'address3': None,
   'city': 'Miami',
   'zip_code': '33150',
   'country': 'US',
   'state': 'FL',
   'display_address': ['150 NW 73rd St', 'Miami, FL 33150']},
  'phone': '+17862149076',
  'display_phone': '(786) 214-9076',
  'distance': 13321.616279262873},
 {'id': 'z1UW-zeI50bMEtGKFtrjmA',
  'alias': 'grails-miami-restaurant-and-sports-bar-miami',
  'name': 'Grails Miami - Restaurant & Sports Bar',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/XU08RveGxutYa-B_2qcClQ/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/grails-miami-restaurant-and-sports-bar-miami?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 776,
  'categories': [{'alias': 'sportsbars', 'title': 'Sports Bars'},
   {'alias': 'newamerican', 'title': 'New American'},
   {'alias': 'lounges', 'title': 'Lounges'}],
  'rating': 4.4,
  'coordinates': {'latitude': 25.803184, 'longitude': -80.195219},
  'transactions': ['delivery', 'pickup'],
  'price': '$$',
  'location': {'address1': '2800 N Miami Ave',
   'address2': None,
   'address3': '',
   'city': 'Miami',
   'zip_code': '33127',
   'country': 'US',
   'state': 'FL',
   'display_address': ['2800 N Miami Ave', 'Miami, FL 33127']},
  'phone': '+17868704313',
  'display_phone': '(786) 870-4313',
  'distance': 10852.71572211731},
 {'id': 'RgL7D8-10fJk6aAPz9a0tg',
  'alias': 'yamashiro-miami-miami-3',
  'name': 'Yamashiro Miami',
  'image_url': 'https://s3-media0.fl.yelpcdn.com/bphoto/L0iv8RmAlh39M2soak_t2g/o.jpg',
  'is_closed': False,
  'url': 'https://www.yelp.com/biz/yamashiro-miami-miami-3?adjust_creative=GWOCZh9-BmZxtdsAjr7Gug&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=GWOCZh9-BmZxtdsAjr7Gug',
  'review_count': 67,

### 2.3 Extracción y transformación de la información de la pagina

In [9]:
#Transformamos la información recibida en un dataframe de pandas
contador = 0
lista_consolidada = []

while contador < 200:
    params={'term':'restaurants','location': ciudad,'limit':50,'offset':contador}
    response=requests.get(api_url,params=params,headers=headers)

    data=response.json()
    
    df_yelp = pd.json_normalize(
        data["businesses"],
        record_path="categories",
        meta=[
            "id","name","review_count","rating","price",
            ["coordinates","latitude"],
            ["coordinates","longitude"],
            ["location","address1"]
        ],
    sep='_',
    errors='ignore'
    )
    lista_consolidada.append(df_yelp)
    contador += 50

In [10]:
# Informacion general del dataframe original df_yelp
print("\n--- 1.2 Información general del Dataframe ---")
display(df_yelp.info())

--- 1.2 Información general del Dataframe ---
<class 'pandas.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   alias                  107 non-null    str
 1   title                  107 non-null    str
 2   id                     107 non-null    str
 3   name                   107 non-null    str
 4   review_count           107 non-null    object
 5   rating                 107 non-null    object
 6   price                  74 non-null     str
 7   coordinates_latitude   107 non-null    object
 8   coordinates_longitude  107 non-null    object
 9   location_address1      104 non-null    str
dtypes: object(4), str(6)
memory usage: 8.5+ KB

None

In [11]:
# Cantidad de restaurantes obtenidos en cada uno de los 4 limites del bucle (cada uno con 50 restaurantes hasta 200).
for i, df in enumerate(lista_consolidada):
    print(f"DataFrame {i+1}: {len(df)} restaurantes")

DataFrame 1: 101 restaurantes
DataFrame 2: 112 restaurantes
DataFrame 3: 106 restaurantes
DataFrame 4: 107 restaurantes

#### 2.3.1 Integración de Fuentes y Consolidación del Dataset Final

In [12]:
# Unir todos los dataframes obtenidos en uno solo e informacion general del dataframe consolidado df_yelp_consolidado
df_yelp_miami = pd.concat(lista_consolidada, ignore_index=True)
print("\n--- 1.4 Información general del Dataframe consolidado ---")
display(df_yelp_miami.info())

--- 1.4 Información general del Dataframe consolidado ---
<class 'pandas.DataFrame'>
RangeIndex: 426 entries, 0 to 425
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   alias                  426 non-null    str
 1   title                  426 non-null    str
 2   id                     426 non-null    str
 3   name                   426 non-null    str
 4   review_count           426 non-null    object
 5   rating                 426 non-null    object
 6   price                  277 non-null    str
 7   coordinates_latitude   426 non-null    object
 8   coordinates_longitude  426 non-null    object
 9   location_address1      423 non-null    str
dtypes: object(4), str(6)
memory usage: 33.4+ KB

None

##### 2.3.2 Exploración del Dataframe consolidado

In [13]:
# Cantidad de columnas y filas en cada dataframe
print("DataFrame original:")
print(df_yelp.shape)
print("DataFrame consolidado:")
print(df_yelp_miami.shape)

DataFrame original:
(107, 10)
DataFrame consolidado:
(426, 10)

In [14]:
# ver dataframe consolidado
df_yelp_miami.head(10)

,alias,title,id,name,review_count,rating,price,coordinates_latitude,coordinates_longitude,location_address1
0,asianfusion,Asian Fusion,K3ukx2e11xTRtYBU01dmrA,Salty Flame,258,4.3,NaN,25.76022,-80.19267,1414 Brickell Ave
1,steak,Steakhouses,K3ukx2e11xTRtYBU01dmrA,Salty Flame,258,4.3,NaN,25.76022,-80.19267,1414 Brickell Ave
2,cocktailbars,Cocktail Bars,K3ukx2e11xTRtYBU01dmrA,Salty Flame,258,4.3,NaN,25.76022,-80.19267,1414 Brickell Ave
3,cuban,Cuban,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,3192,4.4,$$,25.765607,-80.219218,1442 SW 8th St
4,bars,Bars,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,3192,4.4,$$,25.765607,-80.219218,1442 SW 8th St
5,venues,Venues & Event Spaces,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,3192,4.4,$$,25.765607,-80.219218,1442 SW 8th St
6,italian,Italian,oxtMfBGmVNE18pFVuw7lFg,Fratellino,1901,4.8,$$$,25.74917,-80.26011,264 Miracle Mile
7,sushi,Sushi Bars,O4gh_gZPp1zW9QtC1aMHWw,House of Food Porn,178,4.8,NaN,25.832632,-80.200107,197 NW 62nd St
8,asianfusion,Asian Fusion,O4gh_gZPp1zW9QtC1aMHWw,House of Food Porn,178,4.8,NaN,25.832632,-80.200107,197 NW 62nd St
9,wine_bars,Wine Bars,O4gh_gZPp1zW9QtC1aMHWw,House of Food Porn,178,4.8,NaN,25.832632,-80.200107,197 NW 62nd St

In [15]:
# porcentaje de valores nulos por columna
porcentaje_nulos = df_yelp_miami.isnull().mean() * 100
print("\n--- 1.4 Porcentaje de valores nulos por columna ---")
print(porcentaje_nulos)

--- 1.4 Porcentaje de valores nulos por columna ---
alias                     0.000000
title                     0.000000
id                        0.000000
name                      0.000000
review_count              0.000000
rating                    0.000000
price                    34.976526
coordinates_latitude      0.000000
coordinates_longitude     0.000000
location_address1         0.704225
dtype: float64

In [16]:
filas_con_errores = df_yelp_miami[df_yelp_miami.isnull().any(axis=1)]
print(f"Cantidad de filas con errores: {len(filas_con_errores)}")

Cantidad de filas con errores: 149

In [17]:
print(df_yelp_miami.isnull().sum())

alias                      0
title                      0
id                         0
name                       0
review_count               0
rating                     0
price                    149
coordinates_latitude       0
coordinates_longitude      0
location_address1          3
dtype: int64

#### 2.3.3 Limpieza y transformación columna: "precio"

In [18]:
# Agrupar por columna 'price' y contar la cantidad de filas
agrupado_price = df_yelp_miami.groupby('price').size().reset_index(name='cantidad')
print(agrupado_price)

  price  cantidad
0     $        16
1    $$       189
2   $$$        61
3  $$$$        11

In [19]:
# Reemplazar los valores nulos de la columna 'price' por sin información
price_v2 = "Sin Información"
df_yelp_miami['price'] = df_yelp_miami['price'].fillna(price_v2)

#Agrupar por columna 'price' y contar la cantidad de filas
agrupado_price = df_yelp_miami.groupby('price').size().reset_index(name='cantidad')
print(agrupado_price)

             price  cantidad
0                $        16
1               $$       189
2              $$$        61
3             $$$$        11
4  Sin Información       149

In [20]:
# Homologar elementos de la columna 'price' por "bajo", "medio", "alto" y "muy alto"
df_yelp_miami['price'] = df_yelp_miami['price'].replace({
    '$': 'Bajo',
    '$$': 'Medio',
    '$$$': 'Alto',
    '$$$$': 'Muy Alto'
})
#Agrupar por columna 'price' y contar la cantidad de filas
agrupado_price = df_yelp_miami.groupby('price').size().reset_index(name='cantidad')
print(agrupado_price)

             price  cantidad
0             Alto        61
1             Bajo        16
2            Medio       189
3         Muy Alto        11
4  Sin Información       149

#### 2.3.4 Limpieza de la columna 'location_address1'

In [21]:
# Imputar valor "desconocido" a los valores nulos de la columna 'location_address1'
df_yelp_miami['location_address1'] = df_yelp_miami['location_address1'].fillna('Sin Información')
print("\n--- 1.5 Porcentaje de valores nulos por columna después de la imputación ---")
print(df_yelp_miami.isnull().mean() * 100)

--- 1.5 Porcentaje de valores nulos por columna después de la imputación ---
alias                    0.0
title                    0.0
id                       0.0
name                     0.0
review_count             0.0
rating                   0.0
price                    0.0
coordinates_latitude     0.0
coordinates_longitude    0.0
location_address1        0.0
dtype: float64

### 2.4 Dataframe despues de la limpieza

In [22]:
# Ver la cantidad de resultados antes y despues de convertir la información de la API:
print(f"DataFrame original: {len(df_yelp)} restaurantes")
print(f"DataFrame consolidado: {len(df_yelp_miami)} restaurantes")

DataFrame original: 107 restaurantes
DataFrame consolidado: 426 restaurantes

In [23]:
# Ver como quedó el dataframe consolidado
display(df_yelp_miami.head(10))

,alias,title,id,name,review_count,rating,price,coordinates_latitude,coordinates_longitude,location_address1
0,asianfusion,Asian Fusion,K3ukx2e11xTRtYBU01dmrA,Salty Flame,258,4.3,Sin Información,25.76022,-80.19267,1414 Brickell Ave
1,steak,Steakhouses,K3ukx2e11xTRtYBU01dmrA,Salty Flame,258,4.3,Sin Información,25.76022,-80.19267,1414 Brickell Ave
2,cocktailbars,Cocktail Bars,K3ukx2e11xTRtYBU01dmrA,Salty Flame,258,4.3,Sin Información,25.76022,-80.19267,1414 Brickell Ave
3,cuban,Cuban,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,3192,4.4,Medio,25.765607,-80.219218,1442 SW 8th St
4,bars,Bars,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,3192,4.4,Medio,25.765607,-80.219218,1442 SW 8th St
5,venues,Venues & Event Spaces,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,3192,4.4,Medio,25.765607,-80.219218,1442 SW 8th St
6,italian,Italian,oxtMfBGmVNE18pFVuw7lFg,Fratellino,1901,4.8,Alto,25.74917,-80.26011,264 Miracle Mile
7,sushi,Sushi Bars,O4gh_gZPp1zW9QtC1aMHWw,House of Food Porn,178,4.8,Sin Información,25.832632,-80.200107,197 NW 62nd St
8,asianfusion,Asian Fusion,O4gh_gZPp1zW9QtC1aMHWw,House of Food Porn,178,4.8,Sin Información,25.832632,-80.200107,197 NW 62nd St
9,wine_bars,Wine Bars,O4gh_gZPp1zW9QtC1aMHWw,House of Food Porn,178,4.8,Sin Información,25.832632,-80.200107,197 NW 62nd St

### 2.5 Exportación archivo a csv

In [24]:
# exportar csv
df_yelp_miami.to_csv('df_yelp_miami.csv', index=False)